# Postgres com pgAdmin4, configuração básica para primeiro acesso
# Author: Leandro Costa Garcia
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: user
    ports:
      - "15432:5432"
    volumes:
      - ./PostgreSQL:/var/lib/postgresql/data 
    networks:
      - postgres-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@user.com"
      PGADMIN_DEFAULT_PASSWORD: "pg@dmin"
    ports:
      - "16300:80"
    depends_on:
      - db
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge